# Generated by Django 5.2.17 on 2026-08-27 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalonStaff",
        ),
    ]
