# Generated by Django 5.2.17 on 2026-09-01 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_delete_salonstaff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
