# Generated by Django 5.2.17 on 2026-09-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="preferred_language",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
