# Generated by Django 5.2.17 on 2026-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customer_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="session_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
