# Generated by Django 5.2.17 on 2026-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_salon_salon_currency_iso_4217"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="contact_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="salon",
            constraint=models.CheckConstraint(
                condition=models.Q(("contact_email__gt", "")), name="salon_contact_email_not_empty"
            ),
        ),
    ]
