# Generated by Django 5.2.17 on 2026-09-09 09:28

import django.db.models.fields.json
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_salon_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salon",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="salon",
            name="about",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="salon",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name="salon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    django.db.models.lookups.LessThanOrEqual(
                        django.db.models.functions.text.Length(
                            django.db.models.fields.json.KeyTextTransform("en", "about")
                        ),
                        models.Value(2000),
                    ),
                    django.db.models.lookups.LessThanOrEqual(
                        django.db.models.functions.text.Length(
                            django.db.models.fields.json.KeyTextTransform("uk", "about")
                        ),
                        models.Value(2000),
                    ),
                ),
                name="salon_about_max_length_2000_per_language",
            ),
        ),
    ]
