# Generated by Django 5.2.17 on 2026-09-09 09:28

import django.db.models.fields.json
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_catalog_is_active_ordering_service_name_uniq"),
        ("tenants", "0006_alter_salon_options_salon_about_alter_salon_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["ordering", "id"]},
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={"ordering": ["ordering", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="service",
            name="service_salon_name_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="servicecategory",
            name="servicecategory_salon_name_uniq",
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                models.F("salon"),
                catalog.models.NullIf(
                    django.db.models.fields.json.KeyTextTransform("en", "name"), models.Value("")
                ),
                name="service_salon_name_en_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                models.F("salon"),
                catalog.models.NullIf(
                    django.db.models.fields.json.KeyTextTransform("uk", "name"), models.Value("")
                ),
                name="service_salon_name_uk_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                models.F("salon"),
                catalog.models.NullIf(
                    django.db.models.fields.json.KeyTextTransform("en", "name"), models.Value("")
                ),
                name="servicecategory_salon_name_en_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                models.F("salon"),
                catalog.models.NullIf(
                    django.db.models.fields.json.KeyTextTransform("uk", "name"), models.Value("")
                ),
                name="servicecategory_salon_name_uk_uniq",
            ),
        ),
    ]
