# Generated by Django 5.2.17 on 2026-09-11 09:23

import catalog.models
import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_service_options_alter_servicecategory_options_and_more'),
        ('tenants', '0006_alter_salon_options_salon_about_alter_salon_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='service_salon_name_en_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='service_salon_name_uk_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='servicecategory',
            name='servicecategory_salon_name_en_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='servicecategory',
            name='servicecategory_salon_name_uk_uniq',
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(models.F('salon'), catalog.models.NullIf(django.db.models.fields.json.KeyTextTransform('en', 'name'), models.Value(''), output_field=models.TextField()), name='service_salon_name_en_uniq'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(models.F('salon'), catalog.models.NullIf(django.db.models.fields.json.KeyTextTransform('uk', 'name'), models.Value(''), output_field=models.TextField()), name='service_salon_name_uk_uniq'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(models.F('salon'), catalog.models.NullIf(django.db.models.fields.json.KeyTextTransform('en', 'name'), models.Value(''), output_field=models.TextField()), name='servicecategory_salon_name_en_uniq'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(models.F('salon'), catalog.models.NullIf(django.db.models.fields.json.KeyTextTransform('uk', 'name'), models.Value(''), output_field=models.TextField()), name='servicecategory_salon_name_uk_uniq'),
        ),
    ]
