# Generated by Django 5.2.17 on 2026-09-03 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notification_exactly_one_recipient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
    ]
