# Generated by Django 5.2.17 on 2026-09-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_remove_notification_notification_exactly_one_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                default="pending",
                max_length=16,
            ),
        ),
    ]
