# Generated by Django 5.2.17 on 2026-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("booking_created", "Booking created"),
                    ("booking_confirmed", "Booking confirmed"),
                    ("booking_cancelled", "Booking cancelled"),
                    ("booking_expired", "Booking expired"),
                    ("appointment_reminder", "Appointment reminder"),
                    ("payment_succeeded", "Payment succeeded"),
                    ("payment_failed", "Payment failed"),
                    ("review_request", "Review request"),
                    ("email_verification", "Email verification"),
                ],
                max_length=32,
            ),
        ),
    ]
