# Generated by Django 5.2.17 on 2026-09-20 09:57
# Hand-edited: added backfill_booking_link_mode (see docs/DECISIONS.md § Stage
# 15 planning, item 5, Cycle C).

from django.db import migrations, models


def backfill_booking_link_mode(apps, schema_editor):
    """
    Every BOOKING_CREATED Notification that already exists predates this
    field and was recorded by create_guest_appointment -- the only call site
    that has ever dispatched that trigger -- so every one of them is a guest
    booking. `Notification.objects` in this historical model is Django's
    plain auto-generated manager (custom managers, including
    core.models.TenantScopedManager, aren't carried into migration state
    unless a manager sets `use_in_migrations = True`, which
    TenantScopedManager does not), so this runs unscoped across every salon
    with no tenant_context needed -- the same as
    accounts/migrations/0002_alter_user_managers_remove_user_username_and_more.py's
    delete_blank_email_users.
    """
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(trigger_type="booking_created").update(
        booking_link_mode="guest"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_notification_trigger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="booking_link_mode",
            field=models.CharField(
                blank=True,
                choices=[("guest", "Guest"), ("account", "Account")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_booking_link_mode,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
