# Generated by Django 5.2.17 on 2026-09-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("specialists", "0003_specialist_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterField(
            model_name="specialist",
            name="bio",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="name",
            field=models.JSONField(default=dict),
        ),
    ]
