# Generated by Django 5.2.17 on 2026-09-08 14:36

import django.db.models.deletion
from django.db import migrations, models

from core.db import composite_tenant_fk


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_customer_user"),
        ("booking", "0003_alter_appointment_hold_expires_at"),
        ("reviews", "0001_initial"),
        ("specialists", "0003_specialist_photo"),
        ("tenants", "0005_salon_contact_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="hidden_at",
        ),
        migrations.AddField(
            model_name="review",
            name="specialist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="specialists.specialist",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("text__length__lte", 2000)), name="review_text_max_length_2000"
            ),
        ),
        # Composite tenant FK for the new specialist column, mirroring the
        # appointment_id / customer_id guards on this model (and
        # Appointment.specialist_id): a Review's specialist must belong to
        # the same salon as the Review. Django's single-column FK can't
        # express this (core/db.py).
        composite_tenant_fk(
            child_table="reviews_review",
            fk_column="specialist_id",
            parent_table="specialists_specialist",
            constraint_name="reviews_review_specialist_composite_fk",
        ),
    ]
