# Generated by Django 5.2.17 on 2026-08-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payment_payment_currency_iso_4217"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_initiated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
