# Generated by Django 5.2.17 on 2026-09-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_payment_refund_initiated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider_data",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
