# Generated by Django 5.2.17 on 2026-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_payment_provider_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider_reference_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
